In [42]:
import pandas as pd

## **CASECN**

### CASECN [Mapped OCC Data]

In [43]:
df_casecn_mapped = pd.read_csv('talend_output/CPEMS_FRLC_CASECN_OCC_20260125_MappedOCC.csv')

casecn_mapped_cols = ['Id', 
               'Resource_ID',
               'Trading_Hour',
               'Reasons', 
               'Date_From', 
               'Date_To',
               'Brief_Description', 
               'Attachments',
               'Registered_Capacity',
               'Offered_Capacity', 
               'Total_Offered_Capacity', 
               'Seasonal_Max_Capability',
               'Has_Outage'
]

df_casecn_mapped[casecn_mapped_cols]

,Id,Resource_ID,Trading_Hour,Reasons,Date_From,Date_To,Brief_Description,Attachments,Registered_Capacity,Offered_Capacity,Total_Offered_Capacity,Seasonal_Max_Capability,Has_Outage
0,17835169,01CASECN_U02,2026-01-25 01:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,0
1,17835170,01CASECN_U02,2026-01-25 02:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,0
2,17835171,01CASECN_U02,2026-01-25 03:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,0
3,17835172,01CASECN_U02,2026-01-25 04:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,0
4,17835173,01CASECN_U02,2026-01-25 05:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,0
5,17835174,01CASECN_U02,2026-01-25 06:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,0
6,17835175,01CASECN_U02,2026-01-25 07:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,0
7,17835176,01CASECN_U02,2026-01-25 08:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,0
8,17835177,01CASECN_U02,2026-01-25 09:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,0
9,17835178,01CASECN_U02,2026-01-25 10:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,60.0,144,1
10,17835179,01CASECN_U02,2026-01-25 11:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,1
11,17835180,01CASECN_U02,2026-01-25 12:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,1
12,17835181,01CASECN_U02,2026-01-25 13:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,0
13,17835182,01CASECN_U02,2026-01-25 14:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,0
14,17835183,01CASECN_U02,2026-01-25 15:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,0
15,17835184,01CASECN_U02,2026-01-25 16:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,0
16,17835185,01CASECN_U02,2026-01-25 17:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,1
17,17835186,01CASECN_U02,2026-01-25 18:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,1
18,17835187,01CASECN_U02,2026-01-25 19:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,1
19,17835188,01CASECN_U02,2026-01-25 20:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,75.0,144,1
20,17835189,01CASECN_U02,2026-01-25 21:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,1
21,17835190,01CASECN_U02,2026-01-25 22:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,1
22,17835191,01CASECN_U02,2026-01-25 23:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,1
23,17835192,01CASECN_U02,2026-01-26 00:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,1
24,17835145,01CASECN_U01,2026-01-25 01:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
25,17835146,01CASECN_U01,2026-01-25 02:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
26,17835147,01CASECN_U01,2026-01-25 03:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
27,17835148,01CASECN_U01,2026-01-25 04:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
28,17835149,01CASECN_U01,2026-01-25 05:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
29,17835150,01CASECN_U01,2026-01-25 06:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
30,17835151,01CASECN_U01,2026-01-25 07:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
31,17835152,01CASECN_U01,2026-01-25 08:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
32,17835153,01CASECN_U01,2026-01-25 09:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
33,17835154,01CASECN_U01,2026-01-25 10:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,60.0,60.0,144,0
34,17835161,01CASECN_U01,2026-01-25 17:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
35,17835162,01CASECN_U01,2026-01-25 18:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
36,17835163,01CASECN_U01,2026-01-25 19:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
37,17835164,01CASECN_U01,2026-01-25 20:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,75.0,75.0,144,0
38,17835165,01CASECN_U01,2026-01-25 21:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,0
39,17835166,01CASECN_U01,2026-01-25 22:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,0
40,17835167,01CASECN_U01,2026-01-25 23:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,0
41,17835168,01CASECN_U01,2026-01-26 00:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN,82.5,0.0,0.0,144,0

### CASECN [Submitted Data]

In [44]:
df_casecn = pd.read_csv('talend_output/CPEMS_FRLC_CASECN_OCC_20260125_SUBMIT.csv')

casecn_cols = ['Id', 
               'Resource_ID',
               'Trading_Hour',
               'Reasons', 
               'Date_From', 
               'Date_To',
               'Brief_Description', 
               'File'
]

df_casecn[casecn_cols]

,Id,Resource_ID,Trading_Hour,Reasons,Date_From,Date_To,Brief_Description,File
0,17835178,01CASECN_U02,2026-01-25 10:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
1,17835179,01CASECN_U02,2026-01-25 11:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
2,17835180,01CASECN_U02,2026-01-25 12:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
3,17835185,01CASECN_U02,2026-01-25 17:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
4,17835186,01CASECN_U02,2026-01-25 18:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
5,17835187,01CASECN_U02,2026-01-25 19:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
6,17835188,01CASECN_U02,2026-01-25 20:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
7,17835189,01CASECN_U02,2026-01-25 21:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
8,17835190,01CASECN_U02,2026-01-25 22:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
9,17835191,01CASECN_U02,2026-01-25 23:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
10,17835192,01CASECN_U02,2026-01-26 00:00,NaN,2026-01-25 01:00,2026-01-26 00:00,NaN,NaN
11,17835169,01CASECN_U02,2026-01-25 01:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
12,17835170,01CASECN_U02,2026-01-25 02:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
13,17835171,01CASECN_U02,2026-01-25 03:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
14,17835172,01CASECN_U02,2026-01-25 04:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
15,17835173,01CASECN_U02,2026-01-25 05:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
16,17835174,01CASECN_U02,2026-01-25 06:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
17,17835175,01CASECN_U02,2026-01-25 07:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
18,17835176,01CASECN_U02,2026-01-25 08:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
19,17835177,01CASECN_U02,2026-01-25 09:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
20,17835181,01CASECN_U02,2026-01-25 13:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
21,17835182,01CASECN_U02,2026-01-25 14:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
22,17835183,01CASECN_U02,2026-01-25 15:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
23,17835184,01CASECN_U02,2026-01-25 16:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
24,17835145,01CASECN_U01,2026-01-25 01:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
25,17835146,01CASECN_U01,2026-01-25 02:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
26,17835147,01CASECN_U01,2026-01-25 03:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
27,17835148,01CASECN_U01,2026-01-25 04:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
28,17835149,01CASECN_U01,2026-01-25 05:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
29,17835150,01CASECN_U01,2026-01-25 06:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
30,17835151,01CASECN_U01,2026-01-25 07:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
31,17835152,01CASECN_U01,2026-01-25 08:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
32,17835153,01CASECN_U01,2026-01-25 09:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
33,17835154,01CASECN_U01,2026-01-25 10:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
34,17835161,01CASECN_U01,2026-01-25 17:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
35,17835162,01CASECN_U01,2026-01-25 18:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
36,17835163,01CASECN_U01,2026-01-25 19:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
37,17835164,01CASECN_U01,2026-01-25 20:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
38,17835165,01CASECN_U01,2026-01-25 21:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
39,17835166,01CASECN_U01,2026-01-25 22:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
40,17835167,01CASECN_U01,2026-01-25 23:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...
41,17835168,01CASECN_U01,2026-01-26 00:00,RESOURCE CONSTRAINTS HYDRO,2026-01-25 01:00,2026-01-26 00:00,Water Level and Inflow Constraint. The nominat...,Actual Dispatch Report. \nCHEPP Plant Capabili...

## **PNTBNG**

### PNTBNG [Mappedd OCC Data]

In [45]:
df_pntbng_mapped = pd.read_csv('talend_output/CPEMS_FGHPC_PNTBNG_OCC_20260127_MappedOCC.csv')
pntbng_mapped_cols = ['Id', 
               'Resource_ID',
               'Trading_Hour',
               'Reasons', 
               'Date_From', 
               'Date_To',
               'Brief_Description', 
               'Attachments',
               'Registered_Capacity', 
               'Offered_Capacity', 
               'IDR', 
               'Has_Outage'
]

df_pntbng_mapped[pntbng_mapped_cols]

,Id,Resource_ID,Trading_Hour,Reasons,Date_From,Date_To,Brief_Description,Attachments,Registered_Capacity,Offered_Capacity,IDR,Has_Outage
0,17861425,01PNTBNG_U02,2026-01-27 01:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
1,17861426,01PNTBNG_U02,2026-01-27 02:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
2,17861427,01PNTBNG_U02,2026-01-27 03:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
3,17861428,01PNTBNG_U02,2026-01-27 04:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
4,17861429,01PNTBNG_U02,2026-01-27 05:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
5,17861430,01PNTBNG_U02,2026-01-27 06:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
6,17861431,01PNTBNG_U02,2026-01-27 07:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
7,17861432,01PNTBNG_U02,2026-01-27 08:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
8,17861433,01PNTBNG_U02,2026-01-27 09:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
9,17861434,01PNTBNG_U02,2026-01-27 10:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
10,17861435,01PNTBNG_U02,2026-01-27 11:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
11,17861436,01PNTBNG_U02,2026-01-27 12:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
12,17861437,01PNTBNG_U02,2026-01-27 13:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
13,17861438,01PNTBNG_U02,2026-01-27 14:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
14,17861439,01PNTBNG_U02,2026-01-27 15:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
15,17861440,01PNTBNG_U02,2026-01-27 16:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,0
16,17861441,01PNTBNG_U02,2026-01-27 17:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
17,17861442,01PNTBNG_U02,2026-01-27 18:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
18,17861443,01PNTBNG_U02,2026-01-27 19:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
19,17861444,01PNTBNG_U02,2026-01-27 20:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
20,17861445,01PNTBNG_U02,2026-01-27 21:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
21,17861446,01PNTBNG_U02,2026-01-27 22:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
22,17861447,01PNTBNG_U02,2026-01-27 23:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
23,17861448,01PNTBNG_U02,2026-01-28 00:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,60.0,59.0,115.0,1
24,17860849,01MASIWA_G01,2026-01-27 01:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.7,115.0,0
25,17860850,01MASIWA_G01,2026-01-27 02:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.7,115.0,0
26,17860851,01MASIWA_G01,2026-01-27 03:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
27,17860852,01MASIWA_G01,2026-01-27 04:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
28,17860853,01MASIWA_G01,2026-01-27 05:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
29,17860854,01MASIWA_G01,2026-01-27 06:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
30,17860855,01MASIWA_G01,2026-01-27 07:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
31,17860856,01MASIWA_G01,2026-01-27 08:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
32,17860857,01MASIWA_G01,2026-01-27 09:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.5,115.0,0
33,17860858,01MASIWA_G01,2026-01-27 10:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.3,115.0,0
34,17860859,01MASIWA_G01,2026-01-27 11:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.3,115.0,0
35,17860860,01MASIWA_G01,2026-01-27 12:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.3,115.0,0
36,17860861,01MASIWA_G01,2026-01-27 13:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.3,115.0,0
37,17860862,01MASIWA_G01,2026-01-27 14:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.3,115.0,0
38,17860863,01MASIWA_G01,2026-01-27 15:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
39,17860864,01MASIWA_G01,2026-01-27 16:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
40,17860865,01MASIWA_G01,2026-01-27 17:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
41,17860866,01MASIWA_G01,2026-01-27 18:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
42,17860867,01MASIWA_G01,2026-01-27 19:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
43,17860868,01MASIWA_G01,2026-01-27 20:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
44,17860869,01MASIWA_G01,2026-01-27 21:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
45,17860870,01MASIWA_G01,2026-01-27 22:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
46,17860871,01MASIWA_G01,2026-01-27 23:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0
47,17860872,01MASIWA_G01,2026-01-28 00:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN,12.0,11.4,115.0,0

### PNTBNG [Submitted Data]

In [46]:
df_pntbng = pd.read_csv('talend_output/CPEMS_FGHPC_PNTBNG_OCC_20260127_SUBMIT.csv')

pntbng_cols = ['Id', 
               'Resource_ID',
               'Trading_Hour',
               'Reasons', 
               'Date_From', 
               'Date_To',
               'Brief_Description', 
               'File'
]

df_pntbng[pntbng_cols]

,Id,Resource_ID,Trading_Hour,Reasons,Date_From,Date_To,Brief_Description,File
0,17861434,01PNTBNG_U02,2026-01-27 10:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
1,17861435,01PNTBNG_U02,2026-01-27 11:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
2,17861436,01PNTBNG_U02,2026-01-27 12:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
3,17861441,01PNTBNG_U02,2026-01-27 17:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
4,17861442,01PNTBNG_U02,2026-01-27 18:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
5,17861443,01PNTBNG_U02,2026-01-27 19:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
6,17861444,01PNTBNG_U02,2026-01-27 20:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
7,17861445,01PNTBNG_U02,2026-01-27 21:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
8,17861446,01PNTBNG_U02,2026-01-27 22:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
9,17861447,01PNTBNG_U02,2026-01-27 23:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
10,17861448,01PNTBNG_U02,2026-01-28 00:00,NaN,2026-01-27 01:00,2026-01-28 00:00,NaN,NaN
11,17860849,01MASIWA_G01,2026-01-27 01:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
12,17860850,01MASIWA_G01,2026-01-27 02:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
13,17860851,01MASIWA_G01,2026-01-27 03:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
14,17860852,01MASIWA_G01,2026-01-27 04:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
15,17860853,01MASIWA_G01,2026-01-27 05:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
16,17860854,01MASIWA_G01,2026-01-27 06:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
17,17860855,01MASIWA_G01,2026-01-27 07:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
18,17860856,01MASIWA_G01,2026-01-27 08:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
19,17860857,01MASIWA_G01,2026-01-27 09:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
20,17860858,01MASIWA_G01,2026-01-27 10:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
21,17860859,01MASIWA_G01,2026-01-27 11:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
22,17860860,01MASIWA_G01,2026-01-27 12:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
23,17860861,01MASIWA_G01,2026-01-27 13:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
24,17860862,01MASIWA_G01,2026-01-27 14:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
25,17860863,01MASIWA_G01,2026-01-27 15:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
26,17860864,01MASIWA_G01,2026-01-27 16:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
27,17860865,01MASIWA_G01,2026-01-27 17:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
28,17860866,01MASIWA_G01,2026-01-27 18:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
29,17860867,01MASIWA_G01,2026-01-27 19:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
30,17860868,01MASIWA_G01,2026-01-27 20:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
31,17860869,01MASIWA_G01,2026-01-27 21:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
32,17860870,01MASIWA_G01,2026-01-27 22:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
33,17860871,01MASIWA_G01,2026-01-27 23:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
34,17860872,01MASIWA_G01,2026-01-28 00:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,Water Level and Irrigation Diversion Requireme...,Notice of IDR\n FGHPC DOR
35,17861425,01PNTBNG_U02,2026-01-27 01:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
36,17861426,01PNTBNG_U02,2026-01-27 02:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
37,17861427,01PNTBNG_U02,2026-01-27 03:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
38,17861428,01PNTBNG_U02,2026-01-27 04:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
39,17861429,01PNTBNG_U02,2026-01-27 05:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
40,17861430,01PNTBNG_U02,2026-01-27 06:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
41,17861431,01PNTBNG_U02,2026-01-27 07:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
42,17861432,01PNTBNG_U02,2026-01-27 08:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
43,17861433,01PNTBNG_U02,2026-01-27 09:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
44,17861437,01PNTBNG_U02,2026-01-27 13:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
45,17861438,01PNTBNG_U02,2026-01-27 14:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
46,17861439,01PNTBNG_U02,2026-01-27 15:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report
47,17861440,01PNTBNG_U02,2026-01-27 16:00,RESOURCE CONSTRAINTS HYDRO,2026-01-27 01:00,2026-01-28 00:00,For intervals with AS AGC Operation: To preven...,Notice of IDR\n FGHPC DOR\n PHEPP AGC Test Report